### ISSUE TITLE
Add Duisburg-Essen

### ISSUE THREAD

**Issue by Bayquiri** [HackyHour/HackyHour.github.io#11]
Could you add Duisburg-Essen to the list and create us a repo?
We'll start the HackyHour in april.

**Comment by iimog** [comment]
Awesome! I just invited you to the Organization. Feel free, to create the repo yourself and add Duisburg-Essen to the list :smiley:  If you need any help, just let me know. You can use [this template](https://github.com/HackyHour/template) if you want to, but you don't have to.

**Comment by iimog** [comment]
I hope you had a good start! Your website looks nice, and I like your texts better than the ones on our page :-)
I just added Duisburg-Essen to the list of Locations on the main page.

**Comment by Bayquiri** [comment]
Thank you very much. Next step is a new logo. still work on it. But i will start in april with appointments and i am very excited about it.
