### ISSUE TITLE
Please add Strathclyde (in Glasgow, Scotland)

### ISSUE THREAD

**Issue by bhourahine** [HackyHour/HackyHour.github.io#12]
Hello,

We have a Hacky Hour meeting on the first working Wednesday of each month.

Our web page is at
https://www.strath.ac.uk/science/computerinformationsciences/hackyhour/
and there is also a github organisation at
https://github.com/strathclyde-rse

Thanks!

**Comment by iimog** [comment]
Hi Ben,

I added Strathclyde to the list of HackyHour locations, linking to your webpage. If you would like to add additional information or be represented differently, feel free to send a pull request.

Best regards
Markus

**Comment by bhourahine** [comment]
Many Thanks!
