### ISSUE TITLE
Add Cologne

### ISSUE THREAD

**Issue by konrad** [HackyHour/HackyHour.github.io#2]
Please add Cologne as new location - ideally with an own repo.

**Comment by greatfireball** [comment]
Hey @konrad,
 
I added your own repo and a link on the github pages. The repo is empty. In case you want to clone Würzburg or Göttingen, I am sure it is possible for you otherwise let me know and I will do it.

Best Frank

@iimog maybe a good idea to generate a template repository?

**Comment by konrad** [comment]
Many thanks, @greatfireball!

**Comment by konrad** [comment]
And +1 regarding a template repo!
