### ISSUE TITLE
Hacky hour Tucson

### ISSUE THREAD

**Issue by dlebauer** [HackyHour/HackyHour.github.io#7]
There is a hacky hour in Tucson, AZ, USA Thursdays starting at 4 https://researchbazaar.arizona.edu/

Where: Snakes & Lattes (University Blvd)
When: 4PM - 7PM, every Thursday
What: Hacking + Happy Hour = HackyHour! Every week, researchers, data scientists, and programmers around campus get together. Some people bring their programming problems to get help from those with more experience. Those without projects come to discuss their research, brainstorm new ideas, try out new technologies, or chit chat about data science!

**Comment by iimog** [comment]
Awesome! Thanks for sharing! I added the Tucson HackyHour to the list of locations. Have a great Resbaz next week :smiley:
