### ISSUE TITLE
Add Giessen

### ISSUE THREAD

**Issue by ckubgi** [HackyHour/HackyHour.github.io#8]
Could you add Giessen to the list and create us a repo?
We'll start the HackyHour on 22.06. and host it monthly every 4th wednesday.

**Comment by iimog** [comment]
Awesome! I created a repository: https://github.com/HackyHour/Giessen and invited you (to the HackyHour organization and that specific repo). Please update the `index.md` file to your needs. The website is online at: https://hackyhour.github.io/Giessen/
I also added Giessen to the list of locations here: https://hackyhour.github.io/
Let me know if you have questions or need assistance with anything.

**Comment by ckubgi** [comment]
Thank you!
